server:
  port: 8098
  servlet:
    context-path: /api
spring:
  application:
    name: examservice

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/exam_db
    username: Hanchai
    password: Big!89619

  UserService:
    host: http://localhost:8081/api/user
    endpoint:
      getUser: get-user

restTemplate:
  connectionTimeOut: 5000
  readTimeOut: 10000
